<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
	<ItemGroup>
		<NativeCopyFiles Include="$(MSBuildThisPackageRoot)runtimes\win-x64\native\UnlockerStub.dll" />
	</ItemGroup>

	<Target Name="CopyNativeUnlockerStub" AfterTargets="Build">
		<Copy SourceFiles="@(NativeCopyFiles)"
			  DestinationFolder="$(OutDir)"
			  SkipUnchangedFiles="true" />
	</Target>
</Project>
