<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0-windows</TargetFramework>
		<LangVersion>preview</LangVersion>
		<ImplicitUsings>enable</ImplicitUsings>
		<PublishAot>true</PublishAot>
		<Nullable>enable</Nullable>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<PlatformTarget>x64</PlatformTarget>
		<Version>5.8.0</Version>
		<RootNamespace>$(AssemblyName)</RootNamespace>
		<PackageId>Fischless.UnlockerPatch</PackageId>
		<Authors>GenshinMatrix</Authors>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<RepositoryUrl>https://github.com/GenshinMatrix/UnlockerPatch</RepositoryUrl>
		<PackageProjectUrl>https://github.com/GenshinMatrix/UnlockerPatch</PackageProjectUrl>
		<RepositoryType>git</RepositoryType>
		<PackageTags>ObservableCollections MVVM</PackageTags>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<Description>Unlocker for Unity Patch</Description>
		<PackageIcon>Logo.png</PackageIcon>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<DebugType>portable</DebugType>
		<DebugSymbols>true</DebugSymbols>
		<AllowedOutputExtensionsInPackageBuildOutputFolder>.pdb</AllowedOutputExtensionsInPackageBuildOutputFolder>
		<IncludeSymbols>true</IncludeSymbols>
		<EnableWindowsTargeting>true</EnableWindowsTargeting>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
	</PropertyGroup>

	<ItemGroup>
		<None Include=".\Logo.png">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
		<None Include="..\..\README.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
		<None Include="build\package.targets" Pack="True" PackagePath="\build\$(PackageId).targets" />
		<None Include="build\package.props" Pack="True" PackagePath="\build\$(PackageId).props" />
		<None Include="buildTransitive\package.targets" Pack="True" PackagePath="\buildTransitive\$(PackageId).targets" />
		<None Include="buildTransitive\package.props" Pack="True" PackagePath="\buildTransitive\$(PackageId).props" />
		<Content Include="..\..\x64\Release\UnlockerStub.dll">
			<Pack>True</Pack>
			<PackagePath>lib\net8.0-windows7.0\x64\UnlockerStub.dll</PackagePath>
		</Content>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\UnlockerStub\UnlockerStub.vcxproj">
			<Project>{517821e2-89ad-4ea4-b788-e8948bf27d8d}</Project>
			<Platforms>x64</Platforms>
			<Configuration>Release</Configuration>
		</ProjectReference>
	</ItemGroup>

</Project>
